version: '3'
services:
  app:
    build:
      context: ../infra/docker/8.1/php
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    image: app
    environment:
      WWWUSER: '${WWWUSER}'
      XDEBUG_MODE: '${APP_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${APP_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    command: /work/start-container/start-container
    volumes:
      - '.:/work/backend/'
    ports:
      - '9000:9000'
    depends_on:
      - mysql
      - web
  web:
    build:
      context: ../infra/docker/8.1/nginx
      dockerfile: Dockerfile
    image: web
    ports:
      - '${APP_PORT:-80}:80'
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  mysql-test:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT_TEST:-13306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
volumes:
  mysql:
    driver: local
